services:
  app:
    build: .
    ports:
      - 6565:6565
      - 8080:8080
    environment:
      - AB_BASE_URL=${AB_BASE_URL?}
      - AB_CLIENT_ID=${AB_CLIENT_ID?}
      - AB_CLIENT_SECRET=${AB_CLIENT_SECRET?}
      - AB_NAMESPACE=${AB_NAMESPACE?}
      - ITEM_ID_TO_GRANT=${ITEM_ID_TO_GRANT?}
      - TISANE_PARSE_URL=${TISANE_PARSE_URL?}
      - TISANE_LANGUAGE_CODES=${TISANE_LANGUAGE_CODES?}
      - TISANE_SETTING_FORMAT=${TISANE_SETTING_FORMAT?}
      - TISANE_API_KEY=${TISANE_API_KEY?}
      - TISANE_BAN_COMPETITIVE_LANGUAGE=${TISANE_BAN_COMPETITIVE_LANGUAGE}
      - PERSONAL_ATTACK_MESSAGE=${PERSONAL_ATTACK_MESSAGE}
      - BIGOTRY_MESSAGE=${BIGOTRY_MESSAGE}
      - EXTERNAL_CONTACT_MESSAGE=${EXTERNAL_CONTACT_MESSAGE}
      - PROFANITY_MESSAGE=${PROFANITY_MESSAGE}
      - SEXUAL_ADVANCES_MESSAGE=${SEXUAL_ADVANCES_MESSAGE}
      - ADULT_ONLY_MESSAGE=${ADULT_ONLY_MESSAGE}
      - DATA_LEAK_MESSAGE=${DATA_LEAK_MESSAGE}
      - THREAT_MESSAGE=${THREAT_MESSAGE}
      - ASPNETCORE_ENVIRONMENT=Development
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://host.docker.internal:9411/api/v2/spans   # Zipkin
    extra_hosts:
      - host.docker.internal:host-gateway
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: http://localhost:3100/loki/api/v1/push
    #     mode: non-blocking
    #     max-buffer-size: 4m
    #     loki-retries: "3"